### PR TITLE
Added  Product hunt banner in the bottom corner 

### LINKED ISSUE #26: Product hunt banner in the bottom corner after a few seconds
Since this product is already on producthunt , we definitely need votes to maintain it. 
So one cool way will be opening a banner in the bottom left saying something like please upvote it on product hunt

To maintain a proper ux, the banner should after a seconds for one time

### PR DESCRIPTION
**Pull request by Dhevamuthu**
**Added  Product hunt banner in the bottom corner** 

## Description
This PR introduces a new feature to the application: the Banner component. The Banner component serves as a flexible tool for displaying promotional messages or calls to action on the user interface. It appears at the bottom of the screen by default but can be easily repositioned using custom CSS properties. This addition enhances user engagement by providing a prominent space for important announcements or prompts, contributing to a more dynamic and interactive user experience. In this implementation, the Banner includes a prominent "Upvote" button that directs users to the Product Hunt website upon clicking.

---
## Issue Ticket Number
Fixes #26 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [✅] This change requires a documentation update

---
# Checklist:
-[✅] I have checked to ensure there aren't other open Pull Requests for the same update/change?
-[✅] I have performed a self-review of my own code
-[✅] I have commented my code, particularly in hard-to-understand areas
-[ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
please don't change the package and package.lock file

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
use tailwind for the consistency cause the project is itself done with tailwind

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
please revert back the package and package lock file. Cause modules like react-three are not used still mentioned here

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
Don't use the Banner here. What if user moves to other route?? Use it at the entry point route and make sure it does not appear in the 404 page.
 use it in the hero like the membercontextprovider. Import the component and use it.

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
why you made changes in the bottombars and hero.jsx file ????
You don't need make the hero section to be relative. see the membership modal how it is implemented. try to decouple components as much possible

**Comment by Dhevamuthu** [comment]
> Don't use the Banner here. What if user moves to other route?? Use it at the entry point route and make sure it does not appear in the 404 page. use it in the hero like the membercontextprovider. Import the component and use it.

I'm really sorry @ArnabChatterjee20k 

I don't know how to do all these and tailwind css..
So please unassign me and assign to anyone else

Sorry for the inconvenience caused

**Comment by ArnabChatterjee20k** [comment]
> > Don't use the Banner here. What if user moves to other route?? Use it at the entry point route and make sure it does not appear in the 404 page. use it in the hero like the membercontextprovider. Import the component and use it.
> 
> I'm really sorry @ArnabChatterjee20k
> 
> I don't know how to do all these and tailwind css.. So please unassign me and assign to anyone else
> 
> Sorry for the inconvenience caused
Don't you think , you should try learning it ;)
Anyways I am unassigning you

**Pull request closed without merging**
